### ISSUE TITLE
Admin -> Contests -> Prizes tab -> Add/Edit prize form

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#11]
1. The order of the form fields is going to be:
    1. Title
    2. Price
    3. Count
    4. Is main? - if the is_main field is checked then the next fields become available:
    5. Description
    6. Amazon URL
    7. The three images - Only the first should be required

So this means only main prizes get description, url and images

**Comment by amirgee007** [comment]
please test done
