### ISSUE TITLE
Admin -> Contests -> Edit contest -> Prizes tab

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#12]
Separate tables for main and non-main prizes

Because fields are different for main and non-main prizes the current table should be separated in two tables.

I trust you'll find a nice design here

**Comment by amirgee007** [comment]
https://coreui.io/demo/#tables/tables.html

here are 4 types of tables.
so i think the 3rd one is "Condensed Table" looks great and also taking too less space as compared to main table.
so i will use those two table with some status or color so that those will look seperate.

**Comment by amirgee007** [comment]
done please test
