### ISSUE TITLE
Admin -> Contests -> List/Edit contests

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#13]
Add some design labels to see if the contest is Upcoming, Started, and Ended in the contests list and when editing a contest.

**Comment by amirgee007** [comment]
Upcoming, Started, and Ended will be based on the Dates?

if the end_date is less than today & less than end date then ended otherwise Started.
if the start date is greater than today date then it's upcoming.

there are three cases, right?

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
You got that right

**Comment by amirgee007** [comment]
done please test.
