### ISSUE TITLE
Front -> Join contest action

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#15]
So, in the previous task, an action can become undeletable.

An example of this kind of action will become joining the contest.
A contest's page can be accessed at this URL: http://contestr1.test/contest-{contest_id}

On this page, a Visitor can become an Entrant if he has a valid Amazon order id.

To become an entrant:

1. Choose a prize (not required - first prize is chosen)
2. Enter a valid order id
3. Agree to terms and conditions
4. Hit the Join the contest

If the order id is validated the first `entry_action` is saved in the database.

## This is the actual task:

When someone joins the contest the first undeletable action is saved in the database as an `entry_action`

**Comment by amirgee007** [comment]
done.

but what will be value for the $data ['action_data'] action_data column in the entryactions table? for the issue.

also for the other issue.
$data['points'] = 0; //todo: ask to confirm

what will point default value?

**Comment by amirgee007** [comment]
also need to manage this entry_actions on main admin page?

add delete edit etc or not?
