### ISSUE TITLE
Associate actions to contests

### ISSUE THREAD

**Issue by PMxPgRHsOBDGL2MGpYjb** [PMxPgRHsOBDGL2MGpYjb/nbJo8aIMtqg1G0BhRBLQ#9]
In an edit contest page there's an empty tab called Actions

This is available to Admins

Here we'll have to associate Actions to Contests through the actions_contests relation table.

The tab will contain a drop-down of all un-associated actions to the contest being edited and an associate button.

The moment an Action is associated an entry in the actions_contests table is created with the ids of the action and the contest.

On the Actions tab, for each associated action there must be a form with the following fieds:
Points: |____________| (number 1-99)
Uses: |___| (1-action.default_max)
{ucfirst(json_decode(key_name_1))}: |____________|
{ucfirst(json_decode(key_name_2))}: |____________|
{ucfirst(json_decode(key_name_3))}: |____________|
.
.
.
{ucfirst(json_decode(key_name_n))}: |____________|

Every row  `{ucfirst(json_decode(key_name_1))}: |____________|` like this will be saved in the database exactly like the config_template but with the values given by the Admin

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
In the actions table there's a field called config_template which holds a json string.
Let me give you an example
```
{
    "client_id" : "default_client_id_value",
    "client_secret" : "default_client_secret_value"
}
```

If I json_decode that string it will give me an array like this:
```
[
    "client_id" => "default_client_id_value",
    "client_secret" => "default_client_secret_value"
]
```

The form in the actions tab will look like this
```
foreach ($array as $field_name => $value) {
    echo "$field_name: <input type='text' value='$value'><br />";
}
```

**Comment by amirgee007** [comment]
?

**Comment by PMxPgRHsOBDGL2MGpYjb** [comment]
Very good, It's done
